# Generate strong secrets for production and write them into an .env file.
#
# WHY THIS SCRIPT
#   JWT_SECRET / AI_KEY_SECRET / ADMIN_INIT_PASSWORD must be long random values.
#   Typing them by hand leads to weak values, and passing them on the command line
#   leaks them into shell history. This script generates them and writes .env
#   (which is already excluded by .gitignore).
#
# USAGE
#   # 1) Generate .env with random secrets (recommended)
#   powershell -ExecutionPolicy Bypass -File scripts\generate_secrets.ps1
#
#   # 2) Generate and set your own admin password instead of a random one
#   powershell -ExecutionPolicy Bypass -File scripts\generate_secrets.ps1 -AdminPassword "MyOwn#Pass123"
#
#   # 3) Overwrite an existing .env
#   powershell -ExecutionPolicy Bypass -File scripts\generate_secrets.ps1 -Force
#
#   # 4) Only show what would be generated, do not write anything
#   powershell -ExecutionPolicy Bypass -File scripts\generate_secrets.ps1 -DryRun
#
# IMPORTANT
#   AI_KEY_SECRET encrypts the AI API keys stored in the database.
#   Once the platform has saved any API key, DO NOT change AI_KEY_SECRET --
#   changing it makes the stored ciphertext undecryptable (you would have to
#   re-enter every API key in the admin console).
#
# NOTE: keep this file ASCII-only. Windows PowerShell 5.1 reads BOM-less files
#       as ANSI (GBK on Chinese Windows) and non-ASCII text breaks parsing.

param(
    [string]$AdminPassword = "",
    [string]$OutputPath = "",
    [switch]$Force,
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"
$repoRoot = Split-Path -Parent $PSScriptRoot

if (-not $OutputPath) { $OutputPath = Join-Path $repoRoot "spring-backend\.env" }

function New-RandomSecret {
    param([int]$Bytes = 48)
    # RandomNumberGenerator is cryptographically secure (unlike Get-Random)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $buf = New-Object byte[] $Bytes
    $rng.GetBytes($buf)
    $rng.Dispose()
    # Base64 may contain characters that are awkward in .env files; use URL-safe alphabet
    return [Convert]::ToBase64String($buf).Replace('+', 'A').Replace('/', 'B').Replace('=', '')
}

function New-AdminPassword {
    # Readable-but-strong password: avoids characters that are easy to mistype
    $upper = 'ABCDEFGHJKLMNPQRSTUVWXYZ'
    $lower = 'abcdefghijkmnopqrstuvwxyz'
    $digit = '23456789'
    $symbol = '!@#$%^&*'
    $all = $upper + $lower + $digit + $symbol

    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $chars = New-Object System.Collections.Generic.List[char]

    function PickOne([string]$set) {
        $b = New-Object byte[] 1
        $rng.GetBytes($b)
        return $set[$b[0] % $set.Length]
    }

    $chars.Add((PickOne $upper))
    $chars.Add((PickOne $lower))
    $chars.Add((PickOne $digit))
    $chars.Add((PickOne $symbol))
    for ($i = 0; $i -lt 8; $i++) { $chars.Add((PickOne $all)) }
    $rng.Dispose()

    # Shuffle so the required-class characters are not always at the front
    $arr = $chars.ToArray()
    $shuffle = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    for ($i = $arr.Length - 1; $i -gt 0; $i--) {
        $b = New-Object byte[] 1
        $shuffle.GetBytes($b)
        $j = $b[0] % ($i + 1)
        $tmp = $arr[$i]; $arr[$i] = $arr[$j]; $arr[$j] = $tmp
    }
    $shuffle.Dispose()
    return -join $arr
}

$jwtSecret = New-RandomSecret -Bytes 48
$aiKeySecret = New-RandomSecret -Bytes 48
$opsToken = New-RandomSecret -Bytes 24
if ([string]::IsNullOrWhiteSpace($AdminPassword)) {
    $AdminPassword = New-AdminPassword
}

Write-Host ""
Write-Host "=== Generated secrets (length) ===" -ForegroundColor Cyan
Write-Host ("  JWT_SECRET            {0} chars" -f $jwtSecret.Length)
Write-Host ("  AI_KEY_SECRET         {0} chars" -f $aiKeySecret.Length)
Write-Host ("  ADMIN_INIT_PASSWORD   {0} chars" -f $AdminPassword.Length)
Write-Host ("  OPS_TOKEN             {0} chars  (for local password reset)" -f $opsToken.Length)
Write-Host ""

if ($DryRun) {
    Write-Host "DryRun: nothing written." -ForegroundColor Yellow
    Write-Host ""
    Write-Host "ADMIN_INIT_PASSWORD = $AdminPassword" -ForegroundColor Green
    exit 0
}

if ((Test-Path $OutputPath) -and -not $Force) {
    Write-Host "ERROR: $OutputPath already exists." -ForegroundColor Red
    Write-Host "       Refusing to overwrite: an existing .env may already be in use," -ForegroundColor Yellow
    Write-Host "       and changing AI_KEY_SECRET would make stored AI API keys undecryptable." -ForegroundColor Yellow
    Write-Host "       Use -Force if you really want to replace it." -ForegroundColor Yellow
    exit 1
}

$content = @"
# ==========================================================
# Production environment variables (generated by scripts/generate_secrets.ps1)
# DO NOT COMMIT THIS FILE. It is already listed in .gitignore.
# ==========================================================

# --- Required secrets ---
JWT_SECRET=$jwtSecret
AI_KEY_SECRET=$aiKeySecret
ADMIN_INIT_PASSWORD=$AdminPassword

# --- Local admin password reset endpoint token (see scripts/reset_admin_password.ps1) ---
# Leave empty to disable that endpoint (recommended once you no longer need it).
OPS_TOKEN=$opsToken

# --- Turn on strict security checks: refuse to start if a secret is missing/weak ---
APP_SECURITY_STRICT=true

# --- Database (PostgreSQL) ---
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/laos_agri
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=CHANGE_ME_DB_PASSWORD

# --- Redis (optional) ---
REDIS_HOST=localhost
REDIS_PORT=6379

# --- AI service (FastAPI) ---
AI_SERVICE_URL=http://localhost:8000

# --- Server ---
SERVER_PORT=8080
JWT_EXPIRE_HOURS=24
"@

# UTF-8 without BOM: a BOM would become part of the first key name
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($OutputPath, $content, $utf8NoBom)

Write-Host "OK: written to $OutputPath" -ForegroundColor Green
Write-Host ""
Write-Host "=== NEXT STEPS ===" -ForegroundColor Cyan
Write-Host "  1. Set the real database password in that file (SPRING_DATASOURCE_PASSWORD)"
Write-Host "  2. Start the backend:  cd spring-backend; mvn spring-boot:run"
Write-Host "     (.env is loaded automatically)"
Write-Host "  3. Log in as admin with this password:"
Write-Host ("     {0}" -f $AdminPassword) -ForegroundColor Green
Write-Host "  4. Change it right after logging in (a banner will remind you)"
Write-Host ""
Write-Host "WARNING: never change AI_KEY_SECRET after AI API keys are saved," -ForegroundColor Yellow
Write-Host "         otherwise the stored ciphertext cannot be decrypted." -ForegroundColor Yellow
